[platformio]
src_dir = main

[env:esp32dev]
platform = espressif32 @ ~6.9.0
board = esp32-s3-devkitc-1
framework = espidf

; Configuração do Monitor Serial (baud rate padrão do bootloader do ESP32)
monitor_speed = 115200

; Filtro para decodificar o Core Dump e Backtrace caso o ESP32 trave (Panic)
monitor_filters = esp32_exception_decoder

; Opcional: Força a porta serial (se o PIO não achar automaticamente)
; upload_port = /dev/ttyUSB0   ; (Linux/Mac)
; upload_port = COM3           ; (Windows)
